# Generated by Django 4.0.4 on 2022-04-21 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='Имя')),
                ('mname', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('lname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('ph_numb', models.CharField(max_length=40, null=True, unique=True, verbose_name='Номер телефона')),
                ('gender', models.CharField(max_length=7, verbose_name='Пол')),
                ('st_class', models.PositiveIntegerField(default=1, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='Имя')),
                ('mname', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('lname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('ph_numb', models.CharField(max_length=40, null=True, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_topic', models.CharField(max_length=100, verbose_name='Тема урока')),
                ('grade', models.PositiveIntegerField(null=True, verbose_name='Оценка')),
                ('date_gr', models.DateField(default=datetime.date.today, verbose_name='Дата выставление оценки')),
                ('fgrade', models.PositiveIntegerField(null=True, verbose_name='Итоговая оценка')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
