# Generated by Django 4.0.4 on 2022-04-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1, max_length=16, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='fgrade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговая оценка'),
        ),
    ]
