# Generated by Django 4.0.4 on 2022-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_student_password_alter_grade_fgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=16, verbose_name='Пароль'),
        ),
    ]
