# Generated by Django 4.0.4 on 2022-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
