# Generated by Django 4.0.4 on 2022-04-22 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='date_gr',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='fgrade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='lesson_topic',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_topic', models.CharField(max_length=100, verbose_name='Тема урока')),
                ('date_ls', models.DateField(default=datetime.date.today, verbose_name='Дата урока')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.grade', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgrade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговая оценка')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.student', verbose_name='Ученик')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Итоговая оценка',
                'verbose_name_plural': 'Итоговые оценки',
            },
        ),
    ]
